### ISSUE TITLE
inference.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by ruoxuer** [AILab-CVC/VideoCrafter#62]
![1706436123081](https://github.com/AILab-CVC/VideoCrafter/assets/103406084/032f7a0b-bd35-4279-8e84-dd1f053f179f)
请问，为什么在运行  sh scripts/run_image2video.sh之后，提示找不到这么多的参数呢？模型我已经下载了，放在了文档要求的 checkpoint文件夹。

**Comment by catoapowell** [comment]
I am getting the same issue on WSL.

/mnt/d/Projects/AI/VideoCrafter$ sh scripts/run_text2video.sh --ckpt_path checkpoints\base_512_v2\model.ckpt
: not found_text2video.sh: 2:
: not found_text2video.sh: 5:
: not found_text2video.sh: 8:
@CoLVDM Inference: 2024-02-03-23-41-25
usage: inference.py [-h] [--seed SEED] [--mode MODE] [--ckpt_path CKPT_PATH] [--config CONFIG]
                    [--prompt_file PROMPT_FILE] [--savedir SAVEDIR] [--savefps SAVEFPS] [--n_samples N_SAMPLES]
                    [--ddim_steps DDIM_STEPS] [--ddim_eta DDIM_ETA] [--bs BS] [--height HEIGHT] [--width WIDTH]
                    [--frames FRAMES] [--fps FPS] [--unconditional_guidance_scale UNCONDITIONAL_GUIDANCE_SCALE]
                    [--unconditional_guidance_scale_temporal UNCONDITIONAL_GUIDANCE_SCALE_TEMPORAL]
                    [--cond_input COND_INPUT]
inference.py: error: unrecognized arguments:
scripts/run_text2video.sh: 10: --seed: not found
scripts/run_text2video.sh: 11: --mode: not found
scripts/run_text2video.sh: 12: --ckpt_path: not found
scripts/run_text2video.sh: 13: --config: not found
scripts/run_text2video.sh: 14: --savedir: not found
scripts/run_text2video.sh: 15: --n_samples: not found
scripts/run_text2video.sh: 16: --bs: not found
scripts/run_text2video.sh: 17: --unconditional_guidance_scale: not found
scripts/run_text2video.sh: 18: --ddim_steps: not found
scripts/run_text2video.sh: 19: --ddim_eta: not found
scripts/run_text2video.sh: 20: --prompt_file: not found
scripts/run_text2video.sh: 21: --fps: not found

**Comment by catoapowell** [comment]
Replacing args = parser.parse_args()
with 
args, unknown = parser.parse_known_args()
in scripts\evaluation\inference.py 
seems to be a temporary fix, it will still show the "not found" errors, but the program will actually run at least.
now it is displaying other issues though.

Traceback (most recent call last):
  File "/mnt/d/Projects/AI/VideoCrafter/scripts/evaluation/inference.py", line 131, in <module>
    run_inference(args, gpu_num, rank)
  File "/mnt/d/Projects/AI/VideoCrafter/scripts/evaluation/inference.py", line 21, in run_inference
    config = OmegaConf.load(args.config)
  File "/home/echo/.local/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 188, in load
    raise TypeError("Unexpected file type")

**Comment by catoapowell** [comment]
open the file scripts\evaluation\Inference.py in a text editor

Change  args = parser.parse_args() to  args, unknown = parser.parse_known_args()
that fixes the first issue, but the next error is

 Traceback (most recent call last):
  File "/mnt/d/Projects/AI/VideoCrafter/scripts/evaluation/inference.py", line 132, in <module>
    run_inference(args, gpu_num, rank)
  File "/mnt/d/Projects/AI/VideoCrafter/scripts/evaluation/inference.py", line 21, in run_inference
    config = OmegaConf.load(args.config)
  File "/home/echo/.local/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 188, in load
    raise TypeError("Unexpected file type")
